mode: chatops
defaultBranch: develop
branchName: short
autoCloseIssue: true
openPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
commentMessage: "Branch ${branchName} created!\nClone with:\n`git fetch && git checkout --track origin/${branchName}`"
