[build]
  command = "npx pnpm i -r --store=node_modules/.pnpm-store && npx pnpm run build:web3-redux && npx pnpm run build:web3-redux-components-storybook"
  publish = "packages/web3-redux-components/storybook-static"
[build.environment]
  NODE_VERSION = "16"
  NODE_ENV = "development"
  NPM_FLAGS="--version"
