[build.environment]
  NODE_VERSION = "16"
  NODE_ENV = "development"
[build]
  publish = "packages/web3-redux-components/storybook-static"
  command = "npx pnpm i --store=node_modules/.pnpm-store --force && npx pnpm run build"
