name: Issue Branch Actions

on:
  #issues:
  #  types: [assigned]
  # Use chatops only /cib
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14.17"
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
