import Network from './model/interface';
import {
    ETHERSCAN_API_KEY,
    MAINNET_RPC,
    ROPSTEN_RPC,
    RINKEBY_RPC,
    GOERLI_RPC,
    KOVAN_RPC,
    POLYGON_RPC,
    POLYGON_MUMBAI_RPC,
    ARBITRUM_RPC,
    ARBITRUM_RINKEBY_RPC,
    OPTIMISM_RPC,
    OPTIMISM_KOVAN_RPC,
} from '../environment';

export const defaultNetworks: { [networkId: string]: Network } = {
    '1': {
        networkId: '1',
        name: 'Mainnet',
        web3Rpc: MAINNET_RPC,
        explorerUrl: 'https://etherscan.io/',
        explorerApiUrl: 'https://api.etherscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '3': {
        networkId: '3',
        name: 'Ropsten',
        web3Rpc: ROPSTEN_RPC,
        explorerUrl: 'https://ropsten.etherscan.io/',
        explorerApiUrl: 'https://api-ropsten.etherscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '4': {
        networkId: '4',
        name: 'Rinkeby',
        web3Rpc: RINKEBY_RPC,
        explorerUrl: 'https://rinkeby.etherscan.io/',
        explorerApiUrl: 'https://api-rinkeby.etherscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '5': {
        networkId: '5',
        name: 'Goerli',
        web3Rpc: GOERLI_RPC,
        explorerUrl: 'https://goerli.etherscan.io/',
        explorerApiUrl: 'https://api-goerli.etherscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '42': {
        networkId: '42',
        name: 'Kovan',
        web3Rpc: KOVAN_RPC,
        explorerUrl: 'https://kovan.etherscan.io/',
        explorerApiUrl: 'https://api-kovan.etherscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '137': {
        networkId: '137',
        name: 'Polygon',
        web3Rpc: POLYGON_RPC,
        explorerUrl: 'https://polygonscan.io/',
        explorerApiUrl: 'https://api.polygonscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '80001': {
        networkId: '80001',
        name: 'Polygon Mumbai Testnet',
        web3Rpc: POLYGON_MUMBAI_RPC,
        explorerUrl: 'https://testnet.polygonscan.io/',
        explorerApiUrl: 'https://api-testnet.polygonscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '42161': {
        networkId: '42161',
        name: 'Arbitrum One',
        web3Rpc: ARBITRUM_RPC,
        explorerUrl: 'https://arbiscan.io/',
        explorerApiUrl: 'https://api.arbiscan.io/',
        explorerApiKey: ETHERSCAN_API_KEY,
    },
    '421611': {
        networkId: '421611',
        name: 'Arbitrum Rinkeby',
        web3Rpc: ARBITRUM_RINKEBY_RPC,
    },
    '10': {
        networkId: '10',
        name: 'Optimism',
        web3Rpc: OPTIMISM_RPC,
    },
    '69': {
        networkId: '69',
        name: 'Optimism Kovan',
        web3Rpc: OPTIMISM_KOVAN_RPC,
    },
};
